### ISSUE TITLE
Handling reverse-complement duplicates in paired reads

### ISSUE THREAD

**Issue by mikemc** [naobservatory/mgs-workflow#30] opened 2024-06-27 21:57 UTC
Starting an issue to keep track of this limitation in our current implementations of deduplication and duplicate statistics.

Currently the `CLUMPIFY_PAIRED` process has the comment flag "NB: Will NOT handle reverse-complement duplicates". I also believe that duplication statistics are currently being generated from FASTQC, which also does not handle reverse-complement duplicates.

**Comment by mikemc** [comment] 2024-06-28 17:50
After reading the new Readme, I realize this may be effectively handled by the second pass of clumpify following merging (at least in the taxonomic profiling workflow)

**Comment by willbradshaw** [comment] 2024-07-01 18:19
Yeah, this is currently done in the `taxonomy` subworkflow (which also then gets passed to the second half of the `hv` subworkflow), as this is where paired reads get merged into single reads.

I'd like to test the behaviour of this step more extensively, to make absolutely sure that it's handling RC duplicates as we expect. Once that's verified, I'm open to copying this process over to other parts of the pipeline as & when it makes sense.

**Comment by evanfields** [comment] 2024-07-29 18:34
Unfortunately, I don't think clumpify handles reverse complement duplicates, even in non-paired-end mode. Here's a minimal reproducing example, using the same clumpify args (except memory/threads) as `CLUMPIFY_SINGLE`. We start with two short sequences, reverse complements of one another:
```
(NAO) Evans-MacBook-Pro:clumptest evan$ cat mre.fasta
>seq
GGGAAACCCTTT
>seq_rc
AAAGGGTTTCCC

(NAO) Evans-MacBook-Pro:clumptest evan$ /Applications/bbmap/clumpify.sh in=mre.fasta out=mre_out.fasta reorder dedupe containment
/Applications/bbmap//calcmem.sh: line 78: [: -v: unary operator expected
Max memory cannot be determined.  Attempting to use 2000 MB.
If this fails, please add the -Xmx flag (e.g. -Xmx24g) to your command,
or run this program qsubbed or from a qlogin session on Genepool, or set ulimit to an appropriate value.
java -ea -Xmx2000m -Xms2000m -cp /Applications/bbmap/current/ clump.Clumpify in=mre.fasta out=mre_out.fasta reorder dedupe containment
Executing clump.Clumpify [in=mre.fasta, out=mre_out.fasta, reorder, dedupe, containment]
Version 39.08

Read Estimate:          0
Memory Estimate:        0 MB
Memory Available:       1601 MB
Set groups to 1
Executing clump.KmerSort1 [in1=mre.fasta, in2=, out1=mre_out.fasta, out2=, groups=1, ecco=false, rename=false, shortname=f, unpair=false, repair=false, namesort=false, ow=true, reorder, dedupe]

Making comparator.
Made a comparator with k=31, seed=1, border=1, hashes=4
Starting cris 0.
Fetching reads.
Making fetch threads.
Starting threads.
Waiting for threads.
Fetch time: 	0.002 seconds.
Closing input stream.
Combining thread output.
Combine time: 	0.000 seconds.
Sorting.
Sort time: 	0.000 seconds.
Making clumps.
Clump time: 	0.001 seconds.
Deduping.
Dedupe time: 	0.001 seconds.
Writing.
Waiting for writing to complete.
Write time: 	0.001 seconds.
Done!
Time:                         	0.051 seconds.
Reads Processed:             2 	0.04k reads/sec
Bases Processed:            24 	0.00m bases/sec

Reads In:                    2
Clumps Formed:               2
Duplicates Found:            0	0.000%
Reads Out:                   2
Bases Out:                  24
Total time: 	0.125 seconds.

(NAO) Evans-MacBook-Pro:clumptest evan$ cat mre_out.fasta
>seq_rc
AAAGGGTTTCCC
>seq
GGGAAACCCTTT
```

Looking through the available command line options for clumpify, I didn't find a good way to handle RC duplicates. `rcomp` seemed promising but seems to act at the clump level, which doesn't guarantee correcting duplicates across clumps: a sequence and its reverse complement could end up in different clumps and not get the same canonical representation. So`rcomp` doesn't handle this toy case. That said, while the clumpify docs have little to say about how clumps are formed, empirically it seems like maybe for longer sequences, a sequence and its RC do tend to end up in the same clump, or are at least more likely to? In which case a two-pass method could catch some RC duplicates at extra computational cost:
```
clumpify in=in_file.fastq.gz out=intermediate.fastq.gz rcomp reorder
clumpify in=intermediate.fastq.gz out=dedup.fastq.gz reorder dedupe containment
```

Dedupe from bbtools might be an appropriate tool here - certainly the docs are clear that it can handle exact reverse-complement duplicates - but there are also warnings about performance and memory usage on large read sets that seem likely to be binding in our use cases. https://jgi.doe.gov/data-and-tools/software-tools/bbtools/bb-tools-user-guide/dedupe-guide/

**Comment by mikemc** [comment] 2024-07-30 13:04
The trick is to set `passes=2`. With this test file

```
>seq copies=3
GATTACA
>seq_rc copies=5
TGTAATC
>seq_dup
GATTACA
```

and this command,

```sh
clumpify.sh in=test.fasta out=out.fa k=7 rcomp passes=2 dedupe addcount=t
```

the output is

```
>seq copies=9
TGTAATC
```

Note, the clumpify docs actually recommend `passes=6`,

> passes=1 Use this many error-correction passes. 6 passes are
suggested, though more will be more through.

**Comment by willbradshaw** [comment] 2024-09-18 14:36
v2.3.0 now includes multiple passes of Clumpify when running single-ended. However, there appear to be other issues with deduplication beyond this, which I'll flag in a separate issue. Closing this one.

**Closed by willbradshaw** 2024-09-18 14:36 UTC
Labels: bug
